-----------------------------------------------------------ERD Task's Queries---------------------------------------------------------------------

--Use Database:
USE Mart;

-- Select all data from tables:
SELECT * FROM Productline;
SELECT * FROM Office;
SELECT * FROM Employee;
SELECT * FROM Customer;
SELECT * FROM Payment;
SELECT * FROM Order_Table;
SELECT * FROM Order_Product;
SELECT * FROM Product;

--ERD Task's Queries:

1. Select all customers living in California. 
  
2. Find employees with the job title 'Sales Rep'. 
  
3. List products with a price greater than $50. 
  
4. Find orders placed after January 1, 2024. 
  
5. Select payments where the amount is between $100 and $500. 
  
6. Union of customers from California and New York. 
  
7. Intersection of employees and customers with the same email. 
  
8. There is a Difference between products with a quantity in stock over 100 and those less than 50. 
  
9. Union all customers from California and New York (including duplicates). 
  
10. Create a procedure to update customer credit limit. 
  
11. Call the procedure to update the credit limit. 
  
12. Create a procedure to insert a new office. 
  
13. Create a function to get total payments by a customer. 
14. Create a view to list customers and the total value of their orders. 
15. Create a view to list customers with their total orders and payment amount. 
16. Create a view to list products with their stock status (In Stock/Out of Stock). 
17. Create a view to list orders with their customer and employee details. 
18. Create a view to list products with their total order quantities. 
19. Find employees who have not handled any orders. 
20. List the top 5 products by total order quantity. 
21. List employees and the total sales they have handled. 
22. Find the average order value for each customer. 
23. List customers who have placed orders in the last 30 days. 
24. Find the total number of orders and total sales for each product line. 
25. List all products with their vendor names and total quantity ordered. 
26. Find orders that have been partially shipped (i.e., some products are shipped, some are not). 
27. List all customers with more than one order. 
28. Find the total revenue generated by each product. 
29. List all orders with their product details. 
30. Find customers who have made a payment greater than $1000. 
31. List all customers who have orders in the 'Shipped' status. 
32. Count the number of products supplied by each vendor. 
33. Find the average quantity ordered for each product. 
34. List the total number of orders each employee has handled. 
35. List the total sales amount for each customer. 
36. Find the highest payment made by each customer. 
37. List employees and the number of orders they have handled, sorted by the number of orders. 
38. Find the most popular product (by total quantity ordered). 
39. List the total sales amount for each product line. 
40. Create a procedure to add a new product. 
41. Call the procedure to add a new product. 
42. Create a procedure to delete a customer by ID. 
43. Call the procedure to delete a customer. 
44. Create a procedure to add a new order. 
45. Call the procedure to add a new order. 
46. Create a procedure to update the stock quantity of a product. 
47. Call the procedure to update the stock quantity of a product. 
48. Create a procedure to update the order status. 
49. Call the procedure to update the order status. 
50. Create a function to get the total order value for a customer. 
51. Call the function to get total order value for a customer. 
52. Create a function to calculate the total number of employees in a specific office. 
53. Call the function to get the total number of employees in office 1. 
54. Create a function to get the number of orders by status. 
55. Call the function to get the number of shipped orders. 
56. Create a cursor to list all employees who report to a specific manager. 
57. Call the procedure to list employees reporting to a specific manager. 58. Create a cursor to list all orders and their product details. 
59. Call the procedure to list all orders and their product details. 
60. Find the employee who handled the most orders. 
61. List customers and the total value of their orders. 
62. Create a view to list customers with their total orders and total payment amount. 63. Select from the CustomerOrder PaymentSummary view. 
64. Create a view to list products with their stock status (In Stock/Out of Stock). 
65. Select from the ProductStockStatus view. 
66. List all customers who have made no payments. 
67. Find customers who have made no payments. 
68. List the total sales amount for each customer. 
69. Find the highest payment made by each customer. 
70. List employees and the number of orders they have handled, sorted by the number of orders. 
71. Find the most ordered product for each product line. 
72. Create a procedure to insert a new office. 
73. Call the procedure to insert a new office. 
74. Create a function to get total payments by a customer. 
75. Call the function to get total payments by a customer. 
76. Create a procedure using a cursor to list all employees who report to a specific manager. 
77. Call the procedure to list employees reporting to a specific manager. 
78. Create a procedure using a cursor to list all orders and their product details. 
79. Call the procedure to list all orders and their product details. 
80. Create a procedure to update the stock quantity of a product. 
81. Call the procedure to update the stock quantity of a product. 
82. Create a procedure to update the order status. 
83. Call the procedure to update the order status. 
84. Create a function to get the number of orders by status. 
85. Call the function to get the number of shipped orders. 
86. List the total sales amount for each product line. 
87. List the total sales amount for each customer. 
88. Find the highest payment made by each customer. 
89. List employees and the number of orders they have handled. 
90. Find the most ordered product for each product line. 
91. Create a view to list customers and the total value of their orders. 
92. Select from the CustomerOrder Value view. 
93. Find the employee who handled the most orders. 
94. List customers and the total value of their orders.. 
95. Create a view to list customers with their total orders and total payment amount. 
96. Create a view to list products with their stock status (In Stock/Out of Stock). 
97. Create a view to list orders with their customer and employee details. 
98. Create a view to list products with their total order quantities. 
99. Find employees who have not handled any orders. 
100. List the top 5 products by total order quantity. 
